name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -Dquarkus.container-image.registry=ghcr.io -Dquarkus.container-image.image=ghcr.io/kainzpat14/switchbot_proxy quarkus:image-build quarkus:image-push
